CREATE OR REPLACE VIEW gold.v_bc_resources AS
WITH Resources_Aircon AS (
	SELECT 
		r."No"
		,r."Key_No"
		,r."Name"
		,r."Name_2"
		,r."Type"
		,r."Base_Unit_of_Measure"
		,r."Search_Name"
		,r."Resource_Group_No"
		,r."Blocked" 
		,r."Privacy_Blocked"
		,r."Last_Date_Modified"
		,r."Use_Time_Sheet"
		,r."Time_Sheet_Owner_User_ID"
		,r."Time_Sheet_Approver_User_ID"
		,r."Service_Transaction_Type_Code"
		,r."Exclude_From_Service_Decl"
		,r."EDN_Web_Resource"
		,r."EDN_NAV_Key"
		,r."Direct_Unit_Cost"
		,r."Indirect_Cost_Percent"
		,r."Unit_Cost"
		,r."Price_Profit_Calculation"
		,r."Profit_Percent"
		,r."Unit_Price"
		,r."Gen_Prod_Posting_Group"
		,r."VAT_Prod_Posting_Group"
		,r."Default_Deferral_Template_Code"
		,r."Automatic_Ext_Texts"
		,r."IC_Partner_Purch_G_L_Acc_No"
		,r."ITI_Service_Statistical_Code"
		,r."Job_Title"
		,r."Address"
		,r."Address_2"
		,r."City"
		,r."County"
		,r."Post_Code"
		,r."Country_Region_Code"
		,r."Social_Security_No"
		,r."Education"
		,r."Contract_Class"
		,r."Employment_Date"
		,r."SystemModifiedAt"
		,r."load_ts" AS "Load_Date" 
		,'Aircon' AS "Company"
	FROM
		silver.bc_resources_aircon r
),
	
Resources_Technab AS (
	SELECT 
		r."No"
		,r."Key_No"
		,r."Name"
		,r."Name_2"
		,r."Type"
		,r."Base_Unit_of_Measure"
		,r."Search_Name"
		,r."Resource_Group_No"
		,r."Blocked" 
		,r."Privacy_Blocked"
		,r."Last_Date_Modified"
		,r."Use_Time_Sheet"
		,r."Time_Sheet_Owner_User_ID"
		,r."Time_Sheet_Approver_User_ID"
		,r."Service_Transaction_Type_Code"
		,r."Exclude_From_Service_Decl"
		,r."EDN_Web_Resource"
		,r."EDN_NAV_Key"
		,r."Direct_Unit_Cost"
		,r."Indirect_Cost_Percent"
		,r."Unit_Cost"
		,r."Price_Profit_Calculation"
		,r."Profit_Percent"
		,r."Unit_Price"
		,r."Gen_Prod_Posting_Group"
		,r."VAT_Prod_Posting_Group"
		,r."Default_Deferral_Template_Code"
		,r."Automatic_Ext_Texts"
		,r."IC_Partner_Purch_G_L_Acc_No"
		,r."ITI_Service_Statistical_Code"
		,r."Job_Title"
		,r."Address"
		,r."Address_2"
		,r."City"
		,r."County"
		,r."Post_Code"
		,r."Country_Region_Code"
		,r."Social_Security_No"
		,r."Education"
		,r."Contract_Class"
		,r."Employment_Date"
		,r."SystemModifiedAt"
		,r."load_ts" AS "Load_Date" 
		,'Technab' AS "Company"
	FROM
		silver.bc_resources_technab r
),

Resources_Zymetric AS (
	SELECT 
		r."No"
		,r."Key_No"
		,r."Name"
		,r."Name_2"
		,r."Type"
		,r."Base_Unit_of_Measure"
		,r."Search_Name"
		,r."Resource_Group_No"
		,r."Blocked" 
		,r."Privacy_Blocked"
		,r."Last_Date_Modified"
		,r."Use_Time_Sheet"
		,r."Time_Sheet_Owner_User_ID"
		,r."Time_Sheet_Approver_User_ID"
		,r."Service_Transaction_Type_Code"
		,r."Exclude_From_Service_Decl"
		,r."EDN_Web_Resource"
		,r."EDN_NAV_Key"
		,r."Direct_Unit_Cost"
		,r."Indirect_Cost_Percent"
		,r."Unit_Cost"
		,r."Price_Profit_Calculation"
		,r."Profit_Percent"
		,r."Unit_Price"
		,r."Gen_Prod_Posting_Group"
		,r."VAT_Prod_Posting_Group"
		,r."Default_Deferral_Template_Code"
		,r."Automatic_Ext_Texts"
		,r."IC_Partner_Purch_G_L_Acc_No"
		,r."ITI_Service_Statistical_Code"
		,r."Job_Title"
		,r."Address"
		,r."Address_2"
		,r."City"
		,r."County"
		,r."Post_Code"
		,r."Country_Region_Code"
		,r."Social_Security_No"
		,r."Education"
		,r."Contract_Class"
		,r."Employment_Date"
		,r."SystemModifiedAt"
		,r."load_ts" AS "Load_Date" 
		,'Zymetric' AS "Company"
	FROM
		silver.bc_resources_zymetric r
)
	
SELECT *
FROM
	Resources_Aircon
UNION ALL
SELECT *
FROM
	Resources_Technab
UNION ALL
SELECT *
FROM
	Resources_Zymetric
