CREATE OR REPLACE VIEW gold.v_magento_prod_sales_order_item AS
SELECT
	item_id
	,order_id
	,parent_item_id
	,quote_item_id
	,store_id
	,created_at
	,updated_at
	,product_id
	,product_type
	,product_options
	,weight
	,is_virtual
	,sku
	,"name"
	,description
	,applied_rule_ids
	,additional_data
	,is_qty_decimal
	,no_discount
	,qty_backordered
	,qty_canceled
	,qty_invoiced
	,qty_ordered
	,qty_refunded
	,qty_shipped
	,base_cost
	,price
	,base_price
	,original_price
	,base_original_price
	,tax_percent
	,tax_amount
	,base_tax_amount
	,tax_invoiced
	,base_tax_invoiced
	,discount_percent
	,discount_amount
	,base_discount_amount
	,discount_invoiced
	,base_discount_invoiced
	,amount_refunded
	,base_amount_refunded
	,row_total
	,base_row_total
	,row_invoiced
	,base_row_invoiced
	,row_weight
	,base_tax_before_discount
	,tax_before_discount
	,ext_order_item_id
	,locked_do_invoice
	,locked_do_ship
	,price_incl_tax
	,base_price_incl_tax
	,row_total_incl_tax
	,base_row_total_incl_tax
	,discount_tax_compensation_amount
	,base_discount_tax_compensation_amount
	,discount_tax_compensation_invoiced
	,base_discount_tax_compensation_invoiced
	,discount_tax_compensation_refunded
	,base_discount_tax_compensation_refunded
	,tax_canceled
	,discount_tax_compensation_canceled
	,tax_refunded
	,base_tax_refunded
	,discount_refunded
	,base_discount_refunded
	,event_id
	,weee_tax_applied
	,weee_tax_applied_amount
	,weee_tax_applied_row_amount
	,weee_tax_disposition
	,weee_tax_row_disposition
	,base_weee_tax_applied_amount
	,base_weee_tax_applied_row_amnt
	,base_weee_tax_disposition
	,base_weee_tax_row_disposition
	,giftregistry_item_id
	,gift_message_id
	,gift_message_available
	,gw_id
	,gw_base_price
	,gw_price
	,gw_base_tax_amount
	,gw_tax_amount
	,gw_base_price_invoiced
	,gw_price_invoiced
	,gw_base_tax_amount_invoiced
	,gw_tax_amount_invoiced
	,gw_base_price_refunded
	,gw_price_refunded
	,gw_base_tax_amount_refunded
	,gw_tax_amount_refunded
	,free_shipping
	,qty_returned
	,"load_ts"
FROM
	silver.magento_prod_sales_order_item