CREATE OR REPLACE VIEW gold.v_magento_prod_quote_item AS 
SELECT
	item_id
	,quote_id
	,created_at
	,updated_at
	,product_id
	,store_id
	,parent_item_id
	,is_virtual
	,sku
	,"name"
	,description
	,applied_rule_ids
	,additional_data
	,is_qty_decimal
	,no_discount
	,weight
	,qty
	,price
	,base_price
	,custom_price
	,discount_percent
	,discount_amount
	,base_discount_amount
	,tax_percent
	,tax_amount
	,base_tax_amount
	,row_total
	,base_row_total
	,row_total_with_discount
	,row_weight
	,product_type
	,base_tax_before_discount
	,tax_before_discount
	,original_custom_price
	,redirect_url
	,base_cost
	,price_incl_tax
	,base_price_incl_tax
	,row_total_incl_tax
	,base_row_total_incl_tax
	,discount_tax_compensation_amount
	,base_discount_tax_compensation_amount
	,event_id
	,weee_tax_applied
	,weee_tax_applied_amount
	,weee_tax_applied_row_amount
	,weee_tax_disposition
	,weee_tax_row_disposition
	,base_weee_tax_applied_amount
	,base_weee_tax_applied_row_amnt
	,base_weee_tax_disposition
	,base_weee_tax_row_disposition
	,giftregistry_item_id
	,gift_message_id
	,gw_id
	,gw_base_price
	,gw_price
	,gw_base_tax_amount
	,gw_tax_amount
	,free_shipping
	,"load_ts"
FROM
	silver.magento_prod_quote_item