CREATE OR REPLACE VIEW gold.v_magento_prod_quote AS
SELECT
	entity_id
	,store_id
	,created_at
	,updated_at
	,converted_at
	,is_active
	,is_virtual
	,is_multi_shipping
	,items_count
	,items_qty
	,orig_order_id
	,store_to_base_rate
	,store_to_quote_rate
	,base_currency_code
	,store_currency_code
	,quote_currency_code
	,grand_total
	,base_grand_total
	,checkout_method 
	,customer_id
	,customer_tax_class_id
	,customer_group_id
	,customer_email
	,customer_prefix
	,customer_firstname
	,customer_middlename
	,customer_lastname
	,customer_suffix
	,customer_dob
	,customer_note
	,customer_note_notify
	,customer_is_guest
	,remote_ip
	,applied_rule_ids
	,reserved_order_id
	,password_hash
	,coupon_code
	,global_currency_code
	,base_to_global_rate
	,base_to_quote_rate
	,customer_taxvat
	,customer_gender
	,subtotal
	,base_subtotal
	,subtotal_with_discount
	,base_subtotal_with_discount
	,is_changed
	,trigger_recollect
	,ext_shipping_info
	,customer_balance_amount_used
	,base_customer_bal_amount_used
	,use_customer_balance
	,gift_cards
	,gift_cards_amount
	,base_gift_cards_amount
	,gift_cards_amount_used
	,base_gift_cards_amount_used
	,gift_message_id
	,gw_id
	,gw_allow_gift_receipt
	,gw_add_card
	,gw_base_price
	,gw_price
	,gw_items_base_price
	,gw_items_price
	,gw_card_base_price
	,gw_card_price
	,gw_base_tax_amount
	,gw_tax_amount
	,gw_items_base_tax_amount
	,gw_items_tax_amount
	,gw_card_base_tax_amount
	,gw_card_tax_amount
	,gw_base_price_incl_tax
	,gw_price_incl_tax
	,gw_items_base_price_incl_tax
	,gw_items_price_incl_tax
	,gw_card_base_price_incl_tax
	,gw_card_price_incl_tax
	,is_persistent
	,use_reward_points
	,reward_points_balance
	,base_reward_currency_amount
	,reward_currency_amount
	,payment_fee
	,base_payment_fee
	,payment_fee_tax
	,base_payment_fee_tax
	,"load_ts"
FROM
	silver.magento_prod_quote
