CREATE TABLE bronze.bc_reservation_entry_aircon (
	"Entry_No" int4 NOT NULL,
	"Positive" bool NOT NULL,
	"Reservation_Status" text NOT NULL,
	"Item_No" text NOT NULL,
	"Variant_Code" text NULL,
	"Location_Code" text NULL,
	"Serial_No" text NULL,
	"Lot_No" text NULL,
	"Package_No" text NULL,
	"Expected_Receipt_Date" date NOT NULL,
	"Shipment_Date" date NULL,
	"Quantity_Base" int4 NOT NULL,
	"ReservEngineMgt_CreateForText_Rec" text NULL,
	"ReservedFrom" text NULL,
	"Description" text NULL,
	"Source_Type" int4 NOT NULL,
	"Source_Subtype" text NULL,
	"Source_ID" text NULL,
	"Source_Batch_Name" text NULL,
	"Source_Ref_No" int4 NULL,
	"Creation_Date" date NOT NULL,
	"Transferred_from_Entry_No" int4 NULL,
	CONSTRAINT bc_reservation_entry_aircon_pkey PRIMARY KEY ("Entry_No")
);
