------------------------------------------------------------------------------
-- CREATING SERVICE REQUEST TABLES IN SILVER LAYER AND FIRST LOAD
------------------------------------------------------------------------------



CREATE TABLE IF NOT EXISTS silver.oxari_service_request (
	"NUMER_ZLECENIA" text NOT NULL
	,"DATA_ZLECENIA" timestamptz NULL
	,"DATA_ZAMKNIECIA" timestamptz NULL
	,"ZRODLO_ZGLOSZENIA" text NULL
	,"TEMAT" text NULL
	,"AUTOR" text NULL
	,"ZGLASZAJACY" text NULL
	,"ZGLASZAJACY_LOGIN" text NULL
	,"OPIEKUN" text NULL
	,"GRUPA_UZYTKOWNIKOW" text NULL
	,"CZAS_WYKONANIA_MIN" int4 NULL
	,"STATUS_PODJECIA" text NULL
	,"CZAS_PODJECIA" timestamptz NULL
	,"RODZAJ_CZASU" text NULL
	,"CZAS_ROZWIAZANIA_MIN" int4 NULL
	,"RODZAJ_CZASU_R" text NULL
	,"CZAS_WYKONANIA_ROZW_MIN" int4 NULL
	,"OSOBA_WYKONUJACA" text NULL
	,"DZIEN_ODNOTOWANIA_PRACY" timestamptz NULL
	,"DATA_WPROWADZENIA_CZASU_PRACY" timestamptz NULL
	,"TERMINOWOSC_UZUPELNIANIA_CZASU" int4 NULL
	,"DZIENNIK_PRACY_MIN" int4 NULL
	,"STATUS_ZAMYKAJACY" bool NULL
	,"STATUS_ZLECENIA" text NULL
	,"PRIORYTET" text NULL
	,"OCENA_ZADOWOLENIE" int4 NULL
	,"OCENA_UPRZEJMOSC" int4 NULL
	,"OCENA_SKUTECZNOSC" int4 NULL
	,"OCENA_OBSLUGI" int4 NULL
	,"OCENA_CZAS" int4 NULL
	,"CZY_RAZ" bool NULL
	,"UWAGI" text NULL
	,"DATA_MODYF" timestamptz NULL
	,"load_ts" timestamptz NULL
	CONSTRAINT "oxari_Service_request_pkey" PRIMARY KEY ("NUMER_ZLECENIA")
)


-- Pierwsze ładowanie danych z bronze do silver

INSERT INTO silver.oxari_service_request (
	"NUMER_ZLECENIA" 
	,"DATA_ZLECENIA"
	,"DATA_ZAMKNIECIA" 
	,"ZRODLO_ZGLOSZENIA"
	,"TEMAT"
	,"AUTOR"
	,"ZGLASZAJACY"
	,"ZGLASZAJACY_LOGIN"
	,"OPIEKUN"
	,"GRUPA_UZYTKOWNIKOW"
	,"CZAS_WYKONANIA_MIN"
	,"STATUS_PODJECIA"
	,"CZAS_PODJECIA"
	,"RODZAJ_CZASU"
	,"CZAS_ROZWIAZANIA_MIN"
	,"RODZAJ_CZASU_R"
	,"CZAS_WYKONANIA_ROZW_MIN"
	,"OSOBA_WYKONUJACA"
	,"DZIEN_ODNOTOWANIA_PRACY"
	,"DATA_WPROWADZENIA_CZASU_PRACY"
	,"TERMINOWOSC_UZUPELNIANIA_CZASU"
	,"DZIENNIK_PRACY_MIN"
	,"STATUS_ZAMYKAJACY"
	,"STATUS_ZLECENIA"
	,"PRIORYTET"
	,"OCENA_ZADOWOLENIE" 
	,"OCENA_UPRZEJMOSC"
	,"OCENA_SKUTECZNOSC"
	,"OCENA_OBSLUGI"
	,"OCENA_CZAS"
	,"CZY_RAZ"
	,"UWAGI"
	,"DATA_MODYF"
	,"load_ts"
)
		
SELECT
	sr."NUMER_ZLECENIA" 
	,sr."DATA_ZLECENIA"
	,sr."DATA_ZAMKNIECIA" 
	,sr."ZRODLO_ZGLOSZENIA"
	,sr."TEMAT"
	,sr."AUTOR"
	,sr."ZGLASZAJACY"
	,sr."ZGLASZAJACY_LOGIN"
	,sr."OPIEKUN"
	,sr."GRUPA_UZYTKOWNIKOW"
	,sr."CZAS_WYKONANIA_MIN"
	,sr."STATUS_PODJECIA"
	,sr."CZAS_PODJECIA"
	,sr."RODZAJ_CZASU"
	,sr."CZAS_ROZWIAZANIA_MIN"
	,sr."RODZAJ_CZASU_R"
	,sr."CZAS_WYKONANIA_ROZW_MIN"
	,sr."OSOBA_WYKONUJACA"
	,sr."DZIEN_ODNOTOWANIA_PRACY"
	,sr."DATA_WPROWADZENIA_CZASU_PRACY"
	,sr."TERMINOWOSC_UZUPELNIANIA_CZASU"
	,sr."DZIENNIK_PRACY_MIN"
	,sr."STATUS_ZAMYKAJACY"
	,sr."STATUS_ZLECENIA"
	,sr."PRIORYTET"
	,sr."OCENA_ZADOWOLENIE" 
	,sr."OCENA_UPRZEJMOSC"
	,sr."OCENA_SKUTECZNOSC"
	,sr."OCENA_OBSLUGI"
	,sr."OCENA_CZAS"
	,sr."CZY_RAZ"
	,sr."UWAGI"
	,sr."DATA_MODYF"
    ,CURRENT_TIMESTAMP
    
FROM bronze.oxari_service_request  sr

--	ON CONFLICT zostaje dla przeładowania danych po dodaniu doaatkowej kolumny w tabeli

--		ON CONFLICT ("NUMER_ZLECENIA" ) DO UPDATE
--		SET
--		"NUMER_ZLECENIA" = EXCLUDED."NUMER_ZLECENIA"
--		,"DATA_ZLECENIA" = EXCLUDED."DATA_ZLECENIA"
--		,"DATA_ZAMKNIECIA" = EXCLUDED."DATA_ZAMKNIECIA"
--		,"ZRODLO_ZGLOSZENIA" = EXCLUDED."ZRODLO_ZGLOSZENIA"
--		,"TEMAT" = EXCLUDED."TEMAT"
--		,"AUTOR" = EXCLUDED."AUTOR"
--		,"ZGLASZAJACY" = EXCLUDED."ZGLASZAJACY"
--		,"ZGLASZAJACY_LOGIN" = EXCLUDED."ZGLASZAJACY_LOGIN"
--		,"OPIEKUN" = EXCLUDED."OPIEKUN"
--		,"GRUPA_UZYTKOWNIKOW" = EXCLUDED."GRUPA_UZYTKOWNIKOW"
--		,"CZAS_WYKONANIA_MIN" = EXCLUDED."CZAS_WYKONANIA_MIN"
--		,"STATUS_PODJECIA" = EXCLUDED."STATUS_PODJECIA"
--		,"CZAS_PODJECIA" = EXCLUDED."CZAS_PODJECIA"
--		,"RODZAJ_CZASU" = EXCLUDED."RODZAJ_CZASU"
--		,"CZAS_ROZWIAZANIA_MIN" = EXCLUDED."CZAS_ROZWIAZANIA_MIN"
--		,"RODZAJ_CZASU_R" = EXCLUDED."RODZAJ_CZASU_R"
--		,"CZAS_WYKONANIA_ROZW_MIN" = EXCLUDED."CZAS_WYKONANIA_ROZW_MIN"
--		,"OSOBA_WYKONUJACA" = EXCLUDED."OSOBA_WYKONUJACA"
--		,"DZIEN_ODNOTOWANIA_PRACY" = EXCLUDED."DZIEN_ODNOTOWANIA_PRACY"
--		,"DATA_WPROWADZENIA_CZASU_PRACY" = EXCLUDED."DATA_WPROWADZENIA_CZASU_PRACY"
--		,"TERMINOWOSC_UZUPELNIANIA_CZASU" = EXCLUDED."TERMINOWOSC_UZUPELNIANIA_CZASU"
--		,"DZIENNIK_PRACY_MIN" = EXCLUDED."DZIENNIK_PRACY_MIN"
--		,"STATUS_ZAMYKAJACY" = EXCLUDED."STATUS_ZAMYKAJACY"
--		,"STATUS_ZLECENIA" = EXCLUDED."STATUS_ZLECENIA"
--		,"PRIORYTET" = EXCLUDED."PRIORYTET"
--		,"OCENA_ZADOWOLENIE" = EXCLUDED."OCENA_ZADOWOLENIE"
--		,"OCENA_UPRZEJMOSC" = EXCLUDED."OCENA_UPRZEJMOSC"
--		,"OCENA_SKUTECZNOSC" = EXCLUDED."OCENA_SKUTECZNOSC"
--		,"OCENA_OBSLUGI" = EXCLUDED."OCENA_OBSLUGI"
--		,"OCENA_CZAS" = EXCLUDED."OCENA_CZAS"
--		,"CZY_RAZ" = EXCLUDED."CZY_RAZ"
--		,"UWAGI" = EXCLUDED."UWAGI"
--		,"DATA_MODYF" = EXCLUDED."DATA_MODYF"
--		,"load_ts" = CURRENT_TIMESTAMP



--------------------------------------------------------------
-- CREATING DATA LOADING FUNCTION FROM BRONZE TO SILVER LAYER
--------------------------------------------------------------


CREATE OR REPLACE FUNCTION bronze.fn_upsert_oxari_service_request()  -- ZMIENIĆ NAZWĘ FUNKCJI
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$

BEGIN
	INSERT INTO silver.oxari_service_request (
		"NUMER_ZLECENIA" 
		,"DATA_ZLECENIA"
		,"DATA_ZAMKNIECIA" 
		,"ZRODLO_ZGLOSZENIA"
		,"TEMAT"
		,"AUTOR"
		,"ZGLASZAJACY"
		,"ZGLASZAJACY_LOGIN"
		,"OPIEKUN"
		,"GRUPA_UZYTKOWNIKOW"
		,"CZAS_WYKONANIA_MIN"
		,"STATUS_PODJECIA"
		,"CZAS_PODJECIA"
		,"RODZAJ_CZASU"
		,"CZAS_ROZWIAZANIA_MIN"
		,"RODZAJ_CZASU_R"
		,"CZAS_WYKONANIA_ROZW_MIN"
		,"OSOBA_WYKONUJACA"
		,"DZIEN_ODNOTOWANIA_PRACY"
		,"DATA_WPROWADZENIA_CZASU_PRACY"
		,"TERMINOWOSC_UZUPELNIANIA_CZASU"
		,"DZIENNIK_PRACY_MIN"
		,"STATUS_ZAMYKAJACY"
		,"STATUS_ZLECENIA"
		,"PRIORYTET"
		,"OCENA_ZADOWOLENIE" 
		,"OCENA_UPRZEJMOSC"
		,"OCENA_SKUTECZNOSC"
		,"OCENA_OBSLUGI"
		,"OCENA_CZAS"
		,"CZY_RAZ"
		,"UWAGI"
		,"DATA_MODYF"
		,"load_ts"
	)
	SELECT 
		$1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30,$31,$32,$33,$34  -- ilość musi odpowiadać ilości kolumn w tabeli docelowej
		
	ON CONFLICT("NUMER_ZLECENIA" ) DO UPDATE
	SET
		"NUMER_ZLECENIA" = EXCLUDED."NUMER_ZLECENIA"
		,"DATA_ZLECENIA" = EXCLUDED."DATA_ZLECENIA"
		,"DATA_ZAMKNIECIA" = EXCLUDED."DATA_ZAMKNIECIA"
		,"ZRODLO_ZGLOSZENIA" = EXCLUDED."ZRODLO_ZGLOSZENIA"
		,"TEMAT" = EXCLUDED."TEMAT"
		,"AUTOR" = EXCLUDED."AUTOR"
		,"ZGLASZAJACY" = EXCLUDED."ZGLASZAJACY"
		,"ZGLASZAJACY_LOGIN" = EXCLUDED."ZGLASZAJACY_LOGIN"
		,"OPIEKUN" = EXCLUDED."OPIEKUN"
		,"GRUPA_UZYTKOWNIKOW" = EXCLUDED."GRUPA_UZYTKOWNIKOW"
		,"CZAS_WYKONANIA_MIN" = EXCLUDED."CZAS_WYKONANIA_MIN"
		,"STATUS_PODJECIA" = EXCLUDED."STATUS_PODJECIA"
		,"CZAS_PODJECIA" = EXCLUDED."CZAS_PODJECIA"
		,"RODZAJ_CZASU" = EXCLUDED."RODZAJ_CZASU"
		,"CZAS_ROZWIAZANIA_MIN" = EXCLUDED."CZAS_ROZWIAZANIA_MIN"
		,"RODZAJ_CZASU_R" = EXCLUDED."RODZAJ_CZASU_R"
		,"CZAS_WYKONANIA_ROZW_MIN" = EXCLUDED."CZAS_WYKONANIA_ROZW_MIN"
		,"OSOBA_WYKONUJACA" = EXCLUDED."OSOBA_WYKONUJACA"
		,"DZIEN_ODNOTOWANIA_PRACY" = EXCLUDED."DZIEN_ODNOTOWANIA_PRACY"
		,"DATA_WPROWADZENIA_CZASU_PRACY" = EXCLUDED."DATA_WPROWADZENIA_CZASU_PRACY"
		,"TERMINOWOSC_UZUPELNIANIA_CZASU" = EXCLUDED."TERMINOWOSC_UZUPELNIANIA_CZASU"
		,"DZIENNIK_PRACY_MIN" = EXCLUDED."DZIENNIK_PRACY_MIN"
		,"STATUS_ZAMYKAJACY" = EXCLUDED."STATUS_ZAMYKAJACY"
		,"STATUS_ZLECENIA" = EXCLUDED."STATUS_ZLECENIA"
		,"PRIORYTET" = EXCLUDED."PRIORYTET"
		,"OCENA_ZADOWOLENIE" = EXCLUDED."OCENA_ZADOWOLENIE"
		,"OCENA_UPRZEJMOSC" = EXCLUDED."OCENA_UPRZEJMOSC"
		,"OCENA_SKUTECZNOSC" = EXCLUDED."OCENA_SKUTECZNOSC"
		,"OCENA_OBSLUGI" = EXCLUDED."OCENA_OBSLUGI"
		,"OCENA_CZAS" = EXCLUDED."OCENA_CZAS"
		,"CZY_RAZ" = EXCLUDED."CZY_RAZ"
		,"UWAGI" = EXCLUDED."UWAGI"
		,"DATA_MODYF" = EXCLUDED."DATA_MODYF"
		,"load_ts" = CURRENT_TIMESTAMP
	
	USING
		NEW."NUMER_ZLECENIA" 
		,NEW."DATA_ZLECENIA"
		,NEW."DATA_ZAMKNIECIA" 
		,NEW."ZRODLO_ZGLOSZENIA"
		,NEW."TEMAT"
		,NEW."AUTOR"
		,NEW."ZGLASZAJACY"
		,NEW."ZGLASZAJACY_LOGIN"
		,NEW."OPIEKUN"
		,NEW."GRUPA_UZYTKOWNIKOW"
		,NEW."CZAS_WYKONANIA_MIN"
		,NEW."STATUS_PODJECIA"
		,NEW."CZAS_PODJECIA"
		,NEW."RODZAJ_CZASU"
		,NEW."CZAS_ROZWIAZANIA_MIN"
		,NEW."RODZAJ_CZASU_R"
		,NEW."CZAS_WYKONANIA_ROZW_MIN"
		,NEW."OSOBA_WYKONUJACA"
		,NEW."DZIEN_ODNOTOWANIA_PRACY"
		,NEW."DATA_WPROWADZENIA_CZASU_PRACY"
		,NEW."TERMINOWOSC_UZUPELNIANIA_CZASU"
		,NEW."DZIENNIK_PRACY_MIN"
		,NEW."STATUS_ZAMYKAJACY"
		,NEW."STATUS_ZLECENIA"
		,NEW."PRIORYTET"
		,NEW."OCENA_ZADOWOLENIE" 
		,NEW."OCENA_UPRZEJMOSC"
		,NEW."OCENA_SKUTECZNOSC"
		,NEW."OCENA_OBSLUGI"
		,NEW."OCENA_CZAS"
		,NEW."CZY_RAZ"
		,NEW."UWAGI"
		,NEW."DATA_MODYF"
		,CURRENT_TIMESTAMP;

	RETURN NEW;
END;
$function$;



-------------------------------------------------------------------------
-- CREATING TRIGGER IN BRONZE LAYER ON OXARI SERVICE REQUEST TABLE
-------------------------------------------------------------------------



DROP TRIGGER IF EXISTS trg_upsert_oxari_service_request ON bronze.oxari_service_request;
CREATE TRIGGER trg_upsert_oxari_service_request
AFTER INSERT OR UPDATE ON bronze.oxari_service_request
FOR EACH ROW
EXECUTE FUNCTION bronze.fn_upsert_oxari_service_request()